### ISSUE TITLE
setup issue

### ISSUE THREAD

**Issue by Mr-Fang-VLSI** [hkust-zhiyao/RTL-Coder#4]
Hi,

There are some setup issues.

Could you please add the auto-gptq install command in the readme and identify the cuda and python version?

For the CPU version,
Could you please add the ctransformer package install command?

Thanks

**Comment by DevinShang** [comment]
Hi Mr-Fang-VLSI! We have added the setup info you mentioned in the readme file.
Thanks for your issue!
