### ISSUE TITLE
Which model should I use for mle_scoring.py

### ISSUE THREAD

**Issue by markict123** [hkust-zhiyao/RTL-Coder#7]
Hi! I'm trying to use DeepSeek-Coder-6.7b as foundation model for RTLCoder training. But I'm confused about which version I should use. The Base model or the instruct version? Could you share some advice? Thanks.

**Comment by DevinShang** [comment]
Hi, markict123! We recommend you use the instruct version.
It had been carefully trained on the instruction-answer dataset and has a better ability to follow instructions.

**Comment by yyyangzhao** [comment]
Hi! Is the model used in the RTLCoder paper also DeepSeek-Coder6.7b-instruct?
